# A full table of R internals and primitives
# from https://github.com/wch/r-source/blob/b41e8ed455b6bfadc60a6d7bbc8c89fdbddca536/src/main/names.c
# Full R reference with even more functions is here - https://cran.r-project.org/doc/manuals/r-release/fullrefman.pdf
# These internals are the very basic functions. Even the "base" packages are not included here,
# and many of their functions need to be implemented.

_full_R_map_Primitives = {
    "if": None,
    "while": None,
    "for": None,
    "repeat": None,
    "break": None,
    "next": None,
    "return": None,
    "function": None,
    "<-": None,
    "=": None,
    "<<-": None,
    "{": None,
    "(": None,
    ".subset": None,
    ".subset2": None,
    "[": None,
    "[[": None,
    "$": None,
    "@": None,
    "[<-": None,
    "[[<-": None,
    "$<-": None,
    "switch": None,
    "browser": None,
    ".primTrace": None,
    ".primUntrace": None,
    ".Internal": None,
    ".Primitive": None,
    "call": None,
    "quote": None,
    "substitute": None,
    "missing": None,
    "nargs": None,
    "on.exit": None,
    "forceAndCall": None,
}

_full_R_map_dot_Internals = {
    "stop": None,
    "warning": None,
    "gettext": None,
    "ngettext": None,
    "bindtextdomain": None,
    ".addCondHands": None,
    ".addGlobHands": None,
    ".resetCondHands": None,
    ".signalCondition": None,
    ".dfltStop": None,
    ".dfltWarn": None,
    ".addRestart": None,
    ".getRestart": None,
    ".invokeRestart": None,
    ".addTryHandlers": None,
    "geterrmessage": None,
    "seterrmessage": None,
    "printDeferredWarnings": None,
    "interruptsSuspended": None,
    "as.function.default": None,
    "debug": None,
    "undebug": None,
    "isdebugged": None,
    "debugonce": None,
    "Recall": None,
    "delayedAssign": None,
    "makeLazy": None,
    "identical": None,
    "C_tryCatchHelper": None,
}

_full_R_map_Binary = {
    "+": None,
    "-": None,
    "*": None,
    "/": None,
    "^": None,
    "%%": None,
    "%/%": None,
    "%*%": None,

    "==": None,
    "!=": None,
    "<": None,
    "<=": None,
    ">=": None,
    ">": None,
    "&": None,
    "|": None,
    "!": None,

    "&&": None,
    "||": None,
    ":": None,

    "~": None,
}

# VMA = Vectors, Matrices, Arrays
_full_R_map_VMA_Primitives = {
    "...elt": None,
    "...length": None,
    "length": None,
    "length<-": None,
    "c": None,
    "oldClass": None,
    "oldClass<-": None,
    "class": None,
    ".cache_class": None,
    ".class2": None,
    "class<-": None,
    "unclass": None,
    "names": None,
    "names<-": None,
    "dimnames": None,
    "dimnames<-": None,
    "dim": None,
    "dim<-": None,
    "attributes": None,
    "attributes<-": None,
    "attr": None,
    "attr<-": None,
    "@<-": None,
    "levels<-": None,
}

_full_R_map_VMA_dot_Internals = {
    "vector": None,
    "complex": None,
    "matrix": None,
    "array": None,
    "diag": None,
    "backsolve": None,
    "max.col": None,
    "row": None,
    "col": None,
    "unlist": None,
    "cbind": None,
    "rbind": None,
    "drop": None,
    "all.names": None,
    "comment": None,
    "comment<-": None,
    "get": None,
    "get0": None,
    "mget": None,
    "exists": None,
    "assign": None,
    "list2env": None,
    "remove": None,
    "duplicated": None,
    "unique": None,
    "anyDuplicated": None,
    "anyNA": None,
    "which": None,
    "which.min": None,
    "pmin": None,
    "pmax": None,
    "which.max": None,
    "match": None,
    "pmatch": None,
    "charmatch": None,
    "match.call": None,
    "crossprod": None,
    "tcrossprod": None,
    "lengths": None,

    "attach": None,
    "detach": None,
    "search": None,
    "setFileTime": None,
}

_full_R_map_Math = {
    "round": None,
    "signif": None,
    "log": None,
    "log10": None,
    "log2": None,
    "abs": None,
    "floor": None,
    "ceiling": None,
    "sqrt": None,
    "sign": None,
    "trunc": None,

    "exp": None,
    "expm1": None,
    "log1p": None,

    "cos": None,
    "sin": None,
    "tan": None,
    "acos": None,
    "asin": None,
    "atan": None,

    "cosh": None,
    "sinh": None,
    "tanh": None,
    "acosh": None,
    "asinh": None,
    "atanh": None,

    "lgamma": None,
    "gamma": None,

    "digamma": None,
    "trigamma": None,

    "cospi": None,
    "sinpi": None,
    "tanpi": None,

    # Mathematical Functions of Two Numeric (+ 1-2 int) Variables

    "atan2": None,

    "lbeta": None,
    "beta": None,
    "lchoose": None,
    "choose": None,

    "dchisq": None,
    "pchisq": None,
    "qchisq": None,

    "dexp": None,
    "pexp": None,
    "qexp": None,

    "dgeom": None,
    "pgeom": None,
    "qgeom": None,

    "dpois": None,
    "ppois": None,
    "qpois": None,

    "dt": None,
    "pt": None,
    "qt": None,

    "dsignrank": None,
    "psignrank": None,
    "qsignrank": None,

    "besselJ": None,
    "besselY": None,

    "psigamma": None,


    # Mathematical Functions of a Complex Argument

    "Re": None,
    "Im": None,
    "Mod": None,
    "Arg": None,
    "Conj": None,


    # Mathematical Functions of Three Numeric (+ 1-2 int) Variables

    "dbeta": None,
    "pbeta": None,
    "qbeta": None,

    "dbinom": None,
    "pbinom": None,
    "qbinom": None,

    "dcauchy": None,
    "pcauchy": None,
    "qcauchy": None,

    "df": None,
    "pf": None,
    "qf": None,

    "dgamma": None,
    "pgamma": None,
    "qgamma": None,

    "dlnorm": None,
    "plnorm": None,
    "qlnorm": None,

    "dlogis": None,
    "plogis": None,
    "qlogis": None,

    "dnbinom": None,
    "pnbinom": None,
    "qnbinom": None,

    "dnorm": None,
    "pnorm": None,
    "qnorm": None,

    "dunif": None,
    "punif": None,
    "qunif": None,

    "dweibull": None,
    "pweibull": None,
    "qweibull": None,

    "dnchisq": None,
    "pnchisq": None,
    "qnchisq": None,

    "dnt": None,
    "pnt": None,
    "qnt": None,

    "dwilcox": None,
    "pwilcox": None,
    "qwilcox": None,

    "besselI": None,
    "besselK": None,

    "dnbinom_mu": None,
    "pnbinom_mu": None,
    "qnbinom_mu": None,


    # Mathematical Functions of Four Numeric (+ 1-2 int) Variables

    "dhyper": None,
    "phyper": None,
    "qhyper": None,

    "dnbeta": None,
    "pnbeta": None,
    "qnbeta": None,

    "dnf": None,
    "pnf": None,
    "qnf": None,

    "dtukey": None,
    "ptukey": None,
    "qtukey": None,

    # Random numbers
    "rchisq": None,
    "rexp": None,
    "rgeom": None,
    "rpois": None,
    "rt": None,
    "rsignrank": None,

    "rbeta": None,
    "rbinom": None,
    "rcauchy": None,
    "rf": None,
    "rgamma": None,
    "rlnorm": None,
    "rlogis": None,
    "rnbinom": None,
    "rnbinom_mu": None,
    "rnchisq": None,
    "rnorm": None,
    "runif": None,
    "rweibull": None,
    "rwilcox": None,

    "rhyper": None,

    "sample": None,
    "sample2": None,

    "RNGkind": None,
    "set.seed": None,
}

_full_R_map_Data_summaries = {
    "sum": None,
    "min": None,
    "max": None,
    "prod": None,

    "mean": None,
    "range": None,

    "cumsum": None,
    "cumprod": None,
    "cummax": None,
    "cummin": None,
}

_full_R_map_Type_coercions = {
    "as.character": None,
    "as.integer": None,
    "as.double": None,
    "as.numeric": None,
    "as.complex": None,
    "as.logical": None,
    "as.raw": None,
    "as.call": None,
    "as.environment": None,
    "storage.mode<-": None,
    "asCharacterFactor": None,

    "as.vector": None,
    "paste": None,
    "paste0": None,
    "file.path": None,
    "format": None,
    "format.info": None,
    "cat": None,
    "do.call": None,
    "str2lang": None,
    "str2expression": None,
}

_full_R_map_String_manipulations = {
    "nchar": None,
    "nzchar": None,
    "substr": None,
    "startsWith": None,
    "endsWith": None,
    "substr<-": None,
    "strsplit": None,
    "abbreviate": None,
    "make.names": None,
    "pcre_config": None,
    "grep": None,
    "grepl": None,
    "grepRaw": None,
    "sub": None,
    "gsub": None,
    "regexpr": None,
    "gregexpr": None,
    "regexec": None,
    "agrep": None,
    "agrepl": None,
    "adist": None,
    "aregexec": None,
    "tolower": None,
    "toupper": None,
    "chartr": None,
    "sprintf": None,
    "make.unique": None,
    "charToRaw": None,
    "rawToChar": None,
    "rawShift": None,
    "intToBits": None,
    "rawToBits": None,
    "packBits": None,
    "utf8ToInt": None,
    "intToUtf8": None,
    "validUTF8": None,
    "validEnc": None,
    "encodeString": None,
    "iconv": None,
    "strtrim": None,
    "strtoi": None,
    "strrep": None,
}

_full_R_map_Type_checking = {
    "is.null": None,
    "is.logical": None,
    "is.integer": None,
    "is.double": None,
    "is.complex": None,
    "is.character": None,
    "is.symbol": None,
    "is.name": None,
    "is.environment": None,
    "is.list": None,
    "is.pairlist": None,
    "is.expression": None,
    "is.raw": None,

    "is.object": None,
    "isS4": None,

    "is.numeric": None,
    "is.matrix": None,
    "is.array": None,

    "is.atomic": None,
    "is.recursive": None,

    "is.call": None,
    "is.language": None,
    "is.function": None,

    "is.single": None,

    "is.na": None,
    "is.nan": None,
    "is.finite": None,
    "is.infinite": None,

    "is.vector": None,
}

_full_R_map_Misc = {
    # Primitives
    "proc.time": None,
    "gc.time": None,
    "withVisible": None,
    "expression": None,
    "interactive": None,
    "invisible": None,
    "rep": None,
    "rep.int": None,
    "rep_len": None,
    "seq.int": None,
    "seq_len": None,
    "seq_along": None,
    "list": None,
    "xtfrm": None,
    "enc2native": None,
    "enc2utf8": None,

    "emptyenv": None,
    "baseenv": None,
    "globalenv": None,
    "environment<-": None,
    "pos.to.env": None,

    "eapply": None,
    "lapply": None,
    "vapply": None,
    "mapply": None,

    ".C": None,
    ".Fortran": None,
    ".External": None,
    ".External2": None,
    ".Call": None,
    ".External.graphics": None,
    ".Call.graphics": None,

    # .Internal
    "Version": None,
    "machine": None,
    "commandArgs": None,
    "internalsID": None,

    "system": None,

    "shell.exec": None,
    "Sys.which": None,
    "mkjunction": None,
    "tzone_name": None,

    "parse": None,
    "save": None,
    "saveToConn": None,
    "load": None,
    "loadFromConn2": None,
    "loadInfoFromConn2": None,
    "serializeToConn": None,
    "unserializeFromConn": None,
    "serializeInfoFromConn": None,
    "deparse": None,
    "dput": None,
    "dump": None,
    "quit": None,
    "readline": None,
    "print.default": None,
    "prmatrix": None,
    "gc": None,
    "gcinfo": None,
    "gctorture": None,
    "gctorture2": None,
    "memory.profile": None,
    "mem.maxVSize": None,
    "mem.maxNSize": None,
    "split": None,
    "is.loaded": None,
    "recordGraphics": None,
    "dyn.load": None,
    "dyn.unload": None,
    "ls": None,
    "typeof": None,
    "eval": None,
    "returnValue": None,
    "sys.parent": None,
    "sys.call": None,
    "sys.frame": None,
    "sys.nframe": None,
    "sys.calls": None,
    "sys.frames": None,
    "sys.on.exit": None,
    "sys.parents": None,
    "sys.function": None,
    "traceback": None,
    "browserText": None,
    "browserCondition": None,
    "browserSetDebug": None,
    "parent.frame": None,
    "sort": None,
    "is.unsorted": None,
    "sorted_fpass": None,
    "psort": None,
    "qsort": None,
    "radixsort": None,
    "order": None,
    "rank": None,
    "scan": None,
    "t.default": None,
    "aperm": None,
    "builtins": None,
    "args": None,
    "formals": None,
    "body": None,
    "bodyCode": None,
    "environment": None,
    "environmentName": None,
    "env2list": None,
    "reg.finalizer": None,
    "options": None,
    "getOption": None,
    "sink": None,
    "sink.number": None,
    "rapply": None,
    "islistfactor": None,
    "colSums": None,
    "colMeans": None,
    "rowSums": None,
    "rowMeans": None,
    "tracemem": None,
    "retracemem": None,
    "untracemem": None,
    "inspect": None,
    "address": None,
    "named": None,
    "refcnt": None,
    "merge": None,
    "capabilities": None,
    "capabilitiesX11": None,
    "new.env": None,
    "parent.env": None,
    "parent.env<-": None,
    "topenv": None,
    "l10n_info": None,
    "Cstack_info": None,
    "mmap_file": None,
    "munmap_file": None,
    "wrap_meta": None,
    "tryWrap": None,
    "altrep_class": None,
}

_full_R_map_OS = {
    "file.show": None,
    "file.create": None,
    "file.remove": None,
    "file.rename": None,
    "file.append": None,
    "file.symlink": None,
    "file.link": None,
    "file.copy": None,
    "list.files": None,
    "list.dirs": None,
    "file.exists": None,
    "file.choose": None,
    "file.info": None,
    "file.access": None,
    "dir.exists": None,
    "dir.create": None,
    "tempfile": None,
    "tempdir": None,
    "R.home": None,
    "date": None,
    "Sys.getenv": None,
    "Sys.setenv": None,
    "Sys.unsetenv": None,
    "getwd": None,
    "setwd": None,
    "basename": None,
    "dirname": None,
    "Sys.chmod": None,
    "Sys.umask": None,
    "Sys.readlink": None,
    "Sys.info": None,
    "Sys.sleep": None,
    "Sys.getlocale": None,
    "Sys.setlocale": None,
    "Sys.localeconv": None,
    "path.expand": None,
    "Sys.getpid": None,
    "normalizePath": None,
    "Sys.glob": None,
    "unlink": None,
}

_full_R_map_Complex = {
    "polyroot": None,
}

_full_R_map_Objects = {
    "inherits": None,
    "UseMethod": None,
    "NextMethod": None,
    "standardGeneric": None,
}

_full_R_map_Datetime = {
    "Sys.time": None,
    "as.POSIXct": None,
    "as.POSIXlt": None,
    "format.POSIXlt": None,
    "strptime": None,
    "Date2POSIXlt": None,
    "POSIXlt2Date": None,

    "mkCode": None,
    "bcClose": None,
    "is.builtin.internal": None,
    "disassemble": None,
    "bcVersion": None,
    "load.from.file": None,
    "save.to.file": None,
    "growconst": None,
    "putconst": None,
    "getconst": None,
    "enableJIT": None,
    "compilePKGS": None,

    "setNumMathThreads": None,
    "setMaxNumMathThreads": None,
}

_full_R_map_Connections = {
    "stdin": None,
    "stdout": None,
    "stderr": None,
    "isatty": None,
    "readLines": None,
    "writeLines": None,
    "readBin": None,
    "writeBin": None,
    "readChar": None,
    "writeChar": None,
    "open": None,
    "isOpen": None,
    "isIncomplete": None,
    "isSeekable": None,
    "close": None,
    "flush": None,
    "file": None,
    "url": None,
    "pipe": None,
    "fifo": None,
    "gzfile": None,
    "bzfile": None,
    "xzfile": None,
    "unz": None,
    "seek": None,
    "truncate": None,
    "pushBack": None,
    "clearPushBack": None,
    "pushBackLength": None,
    "rawConnection": None,
    "rawConnectionValue": None,
    "textConnection": None,
    "textConnectionValue": None,
    "socketConnection": None,
    "sockSelect": None,
    "getConnection": None,
    "getAllConnections": None,
    "summary.connection": None,
    "gzcon": None,
    "memCompress": None,
    "memDecompress": None,
}

_full_R_map_Others = {
    "readDCF": None,

    "lockEnvironment": None,
    "environmentIsLocked": None,
    "lockBinding": None,
    "unlockBinding": None,
    "bindingIsLocked": None,
    "makeActiveBinding": None,
    "bindingIsActive": None,
    # looks like mkUnbound is unused in base R
    "mkUnbound": None,
    "isNamespaceEnv": None,
    "registerNamespace": None,
    "unregisterNamespace": None,
    "getRegisteredNamespace": None,
    "isRegisteredNamespace": None,
    "getNamespaceRegistry": None,
    "importIntoEnv": None,
    "env.profile": None,

    "Encoding": None,
    "setEncoding": None,
    "setTimeLimit": None,
    "setSessionTimeLimit": None,
    "icuSetCollate": None,
    "icuGetCollate": None,
    "readRenviron": None,
    "shortRowNames": None,
    "copyDFattr": None,
    "getRegisteredRoutines": None,
    "getLoadedDLLs": None,
    "getSymbolInfo": None,
    ".isMethodsDispatchOn": None,
    "lazyLoadDBfetch": None,
    "lazyLoadDBflush": None,
    "getVarsFromFrame": None,
    "lazyLoadDBinsertValue": None,
    "bincode": None,
    "tabulate": None,
    "findInterval": None,
    "pretty": None,
    "formatC": None,
    "crc64": None,
    "bitwiseAnd": None,
    "bitwiseNot": None,
    "bitwiseOr": None,
    "bitwiseXor": None,
    "bitwiseShiftL": None,
    "bitwiseShiftR": None,
    "serialize": None,
    "serializeb": None,
    "unserialize": None,
    "rowsum_matrix": None,
    "rowsum_df": None,
    "setS4Object": None,
    "traceOnOff": None,
    "debugOnOff": None,

    "La_qr_cmplx": None,
    "La_rs": None,
    "La_rs_cmplx": None,
    "La_rg": None,
    "La_rg_cmplx": None,
    "La_rs": None,
    "La_rs_cmplx": None,
    "La_dlange": None,
    "La_dgecon": None,
    "La_dtrcon": None,
    "La_zgecon": None,
    "La_ztrcon": None,
    "La_solve_cmplx": None,
    "La_solve": None,
    "La_qr": None,
    "La_chol": None,
    "La_chol2inv": None,

    "qr_coef_real": None,
    "qr_qy_real": None,
    "det_ge_real": None,
    "qr_coef_cmplx": None,
    "qr_qy_cmplx": None,

    "La_svd": None,
    "La_svd_cmplx": None,
    "La_version": None,
    "La_library": None,

    "bcprofcounts": None,
    "bcprofstart": None,
    "bcprofstop": None,

    "eSoftVersion": None,
    "curlVersion": None,
    "curlGetHeaders": None,
    "curlDownload": None,
}

_full_R_map_Special_symbols = {
    ".Device": None,
    "...": None,
    ".Last.value": None,
    "levels": None,
    "mode": None,
    "name": None,
    "na.rm": None,
    "package": None,
    "previous": None,
    "row.names": None,
    ".Random.seed": None,
    "sort.list": None,
    "source": None,
    "tsp": None,
    ".Environment": None,
    "exact": None,
    "recursive": None,
    "srcfile": None,
    "srcref": None,
    "wholeSrcref": None,
    "*tmp*": None,
    "use.names": None,
    "::": None,
    ":::": None,
    "conn_id": None,
    ".Devices": None,
    "base": None,
    "spec": None,
    ".__NAMESPACE__.": None,

    ".Generic": None,
    ".Method": None,
    ".Methods": None,
    ".defined": None,
    ".target": None,
    ".Group": None,
    ".Class": None,
    ".GenericCallEnv": None,
    ".GenericDefEnv": None,
    ".packageName": None,
}

full_map = dict(
    **_full_R_map_Primitives,
    **_full_R_map_dot_Internals,
    **_full_R_map_Binary,
    **_full_R_map_VMA_Primitives,
    **_full_R_map_VMA_dot_Internals,
    **_full_R_map_Math,
    **_full_R_map_Data_summaries,
    **_full_R_map_Type_coercions,
    **_full_R_map_String_manipulations,
    **_full_R_map_Type_checking,
    **_full_R_map_Misc,
    **_full_R_map_OS,
    **_full_R_map_Complex,
    **_full_R_map_Objects,
    **_full_R_map_Datetime,
    **_full_R_map_Connections,
    **_full_R_map_Others,
    **_full_R_map_Special_symbols,
)
